// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd0w9nDwoQQh4hGrsjpgckD_klOsXApyM',
    appId: '1:410599463243:web:720537807cf30d1a3d70ce',
    messagingSenderId: '410599463243',
    projectId: 'petnest2-2861c',
    authDomain: 'petnest2-2861c.firebaseapp.com',
    storageBucket: 'petnest2-2861c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj__RHSZ3n6oC3fwjPGfgW2oTrU_xYZYg',
    appId: '1:410599463243:android:c9b315e63296261f3d70ce',
    messagingSenderId: '410599463243',
    projectId: 'petnest2-2861c',
    storageBucket: 'petnest2-2861c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8h7s1xrmlNGEfFQ3Q9OKAX7cKU2ENVNA',
    appId: '1:410599463243:ios:2529f31bb997d1a33d70ce',
    messagingSenderId: '410599463243',
    projectId: 'petnest2-2861c',
    storageBucket: 'petnest2-2861c.firebasestorage.app',
    iosBundleId: 'com.example.petnestFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8h7s1xrmlNGEfFQ3Q9OKAX7cKU2ENVNA',
    appId: '1:410599463243:ios:2529f31bb997d1a33d70ce',
    messagingSenderId: '410599463243',
    projectId: 'petnest2-2861c',
    storageBucket: 'petnest2-2861c.firebasestorage.app',
    iosBundleId: 'com.example.petnestFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd0w9nDwoQQh4hGrsjpgckD_klOsXApyM',
    appId: '1:410599463243:web:e4f636be79c222fe3d70ce',
    messagingSenderId: '410599463243',
    projectId: 'petnest2-2861c',
    authDomain: 'petnest2-2861c.firebaseapp.com',
    storageBucket: 'petnest2-2861c.firebasestorage.app',
  );
}
